from django.urls import path
from . import views

urlpatterns = [
    path('', views.say_hello, name="say_hello"),
    path('open_signup', views.open_signup, name="open_signup"),
    path('open_signin', views.open_signin, name="open_signin"),
    path('signup', views.signup, name="signup"),
    path('signin', views.signin, name="signin"),
    path('customer_home/<str:username>/', views.customer_home, name='customer_home'),
    path('open_add_restaurant', views.open_add_restaurant, name="open_add_restaurant"),
    path('add_restaurant', views.add_restaurant, name='add_restaurant'),
    path('open_show_restaurant', views.open_show_restaurant, name='open_show_restaurant'),
    path('open_update_restaurant/<int:restaurant_id>', views.open_update_restaurant, name="open_update_restaurant"),
    path('update_restaurant/<int:restaurant_id>', views.update_restaurant, name="update_restaurant"),
    path('delete_restaurant/<int:restaurant_id>', views.delete_restaurant, name="delete_restaurant"),
    path('open_update_menu/<int:restaurant_id>', views.open_update_menu, name='open_update_menu'), 
    path('update_menu/<int:restaurant_id>', views.update_menu, name='update_menu'),
    path('view_menu/<int:restaurant_id>/<str:username>', views.view_menu, name="view_menu"),
    path('open_edit_item/<int:item_id>/', views.open_edit_item, name='open_edit_item'),
    path('edit_item/<int:item_id>/', views.edit_item, name='edit_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
    path('add_to_cart/<int:item_id>/<str:username>', views.add_to_cart, name="add_to_cart"),
    path('show_cart/<str:username>', views.show_cart, name="show_cart"),
    path('checkout/<str:username>/', views.checkout, name="checkout"),
    path('orders/<str:username>/', views.orders, name="orders"),
    path('increase_quantity/<int:cart_item_id>/', views.increase_quantity, name='increase_quantity'),
    path('decrease_quantity/<int:cart_item_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('delete_cart_item/<int:cart_item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('support/<str:username>/', views.open_support, name='open_support'),
    path('support/<str:username>/submit/', views.submit_ticket, name='submit_ticket'),
    path('admin/tickets/', views.admin_tickets, name='admin_tickets'),
    path('admin/tickets/<int:ticket_id>/resolve/', views.resolve_ticket, name='resolve_ticket'),
    path('admin/tickets/<int:ticket_id>/delete/', views.delete_ticket, name='delete_ticket'),
    path('order_history/<str:username>/', views.order_history, name='order_history'),
    path('reorder/<int:order_id>/', views.reorder, name='reorder'),
]
