# Generated by Django 6.0.5 on 2026-06-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkrD2SYx6llm-j-3IGwADTT2eGb8cfUpdc0Q&s', max_length=20)),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField(max_length=20)),
            ],
        ),
    ]
