# Generated by Django 6.0.5 on 2026-06-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_driver_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
